### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by tomfanxiaojun** [wendaosanshou/fecss-blog#1]
你好，

我想下载你这个Blog，用来学习Vue，但是我 npm install 后，运行：npm run dev 后，页面不出来，显示如下错误信息，是不是ES6的语法，缺少相应的解析包？

请帮忙看看。

![image](https://cloud.githubusercontent.com/assets/6749916/18857797/702bf98c-8499-11e6-81eb-4622c841a471.png)

**Comment by taomas** [comment]
import关键字不能使用应该是`babel-loader`的相关依赖没有安装成功！

你可以尝试一下以下方法。
- 使用淘宝的镜像重新安装依赖，比如先全局安装cnpm，`npm install -g cnpm --registry=https://registry.npm.taobao.org`，然后进入项目后，使用`cnpm install`
- 重新安装babel-loader,可以尝试使用`npm install babel-loader babel-core babel-preset-es2015 --save-dev`来安装babel的相关loader
- 由于该项目是使用vue-cli创建的。我不清楚如果未全局安装vue-cli会不会导致相关问题。可以尝试`npm install vue-cli -g`来全局安装vue-cli

**Comment by taomas** [comment]
该项目运行需要先启动[服务端](https://github.com/wendaosanshou/fecss-blog-api)程序！

**Comment by tomfanxiaojun** [comment]
你好，
1，我已经启动了服务端（服务端，需要npm install pm2 -g,觉得可以放在package.json 中，我们这样的学习者，就不会启动困难了）：
![image](https://cloud.githubusercontent.com/assets/6749916/18858112/50214eaa-849c-11e6-901e-4c37acbcae1a.png)
2，我也单独安装了：npm install vue-cli -g,
重新启动，也还是报错，而且我查看了npm list ,babel 应该都是安装成功的，如图：
![image](https://cloud.githubusercontent.com/assets/6749916/18858184/ae67ae96-849c-11e6-8db0-7527512bd317.png)

![image](https://cloud.githubusercontent.com/assets/6749916/18858206/d119e454-849c-11e6-84b8-baa538a99a76.png)

**Comment by taomas** [comment]
恩恩。谢谢你的建议。

我刚才重新clone了一下。然后使用的淘宝的镜像，`cnpm install`来安装的依赖。
安装完成后发现我的package.json少了一个`js-cookie`的依赖包。安装完成后。
直接`npm run dev`运行是没有问题的。

你能不能用淘宝的镜像重新安装试试看。确实这个项目在vue-cli创建的时候依赖的npm包太多了。

**Comment by tomfanxiaojun** [comment]
我还真不知道淘宝镜像怎么用。公司的网络是可以访问国外网络的。所以必须需要淘宝镜像么？

**Comment by taomas** [comment]
请问一下你在`npm run dev`过程中，命令行有没有报什么错误？

我也实在是想不到为什么`import`关键字不能使用。
因为只要是正常的安装完依赖后，使用`npm run dev`，是能够正常运行项目的。

或者你可以把前面引入css文件的`import`修改为`require`，测试一下是不是正常的。

**Comment by tomfanxiaojun** [comment]
npm install 没有报错，那我试下require.
